---
date: "2021-05-25"
title: "Resume"
output:
  distill::distill_article:
    theme: theme.css
---

## Education
* Ph.D. Candidate in Economics, Goethe University Frankfurt, Frankfurt (Germany), _2019 - Present_
* M.Sc. in Economics, Middle East Technical University, Ankara (Turkey), _2016-2018_
* B.A. in Economics, Bogazici University, Istanbul (Turkey),  _2010-2015_
  
## Employment
* Researcher at Central Bank of the Republic of Turkey, _2016-2019_
  * Research & Monetary Policy Department
      * **Short Term Inflation Forecasting**: Conducted short term macro-econometric modeling and forecasting in the price analysis team using various types of modeling techniques. Mainly used time-varying parameter models, Bayesian VAR Models, disaggregate models, satellite models, and carried out model performance. Furthermore regularly contributed to the quarterly inflation reports, monthly price development releases, and ad hoc policy reports.
      
      * **International Economic Growth**: Wrote policy reports and briefs on international economic developments and their prospective impacts on the economy. Closely following the key economic indicators and macroeconomic data and the impact on the export performance.
  
## Fields of Interest
* Primary
  * Macroeconomics, Applied Econometrics 
* Secondary
  * Machine Learning, Data Science

## Articles

* Nonlinear Dynamics in Exchange Rate Pass Through and Inflation Persistence: The Case of Turkish Economy

## Working Papers

* Uneven Consequences of Coronavirus Pandemic: Evidence from a Real Time Survey

## Grants \& Awards
* Graduate School Fellowship/Scholarship
  * Ph.D. Fellowship

## Personal
* Citizenship :  Turkey
* Languages :  Turkish (Native), English (Fluent), Spanish (Pre-Int), German (Basic)

## Computer Skills
* Julia, Python, R, Matlab/Dynare, Stata, Eviews, Gretl, $\LaTeX$

## Interests
* Professional Photography, Classical Music

---

```{r include=FALSE}
library(kableExtra)
```

Click `r text_spec("[HERE](cv.pdf)", background = "#0D7680", color = "yellow", bold = T)` PDF Version

